config/routes.rb
SMDProject::Application.routes.draw do

  root "pages#index"
  
  resources :sessions, only: [:new, :create, :destroy]  

  resources :members, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :messages, only: [:index, :new, :create, :show, :destroy]
    member do      
      get 'change_password'
      patch 'update_password'
    end
  end

  resources :societies do
    resources :events, only: [:new, :create, :show, :edit, :update, :destroy] do
      resources :reservations, only: [:new, :create, :show, :edit, :update, :destroy]
      resources :comments, only: [:new, :create]
    end
    get 'join', on: :member
    get 'autocomplete', on: :collection
  end
  
 
  match "/search", to: "pages#search", via: [:get, :post], as: :search  
  match "/events", to: "pages#event", via: [:get, :post], as: :eventslist
  match "/registration", to: "members#new", via: [:get, :post]
  match "/login", to: "sessions#new", via: [:get, :post]
  match "/logout", to: "sessions#destroy", via: [:get, :post]
  match "/pages/search_autocomplete", to: "pages#search_autocomplete", via: [:get, :post]

end

app/models/event.rb
class Event < ActiveRecord::Base
  self.inheritance_column = nil
  
  belongs_to :society
  has_one :ticket
  has_many :pictures
  has_many :comments
  has_many :reservations
  has_one :group
     
  accepts_nested_attributes_for :pictures, allow_destroy: true
  accepts_nested_attributes_for :group
  accepts_nested_attributes_for :ticket
        
  validates :name, length: { maximum: 30 }, presence: true, uniqueness: { case_sensitive: false }
  validates :type, length: { maximum: 30 }, presence: true

  validates_date :date_begin, presence: true, :on_or_after => lambda { Date.current }
  validates_date :date_end, presence: true, :on_or_after => :date_begin
  validates_time :time_begin, presence: true
  validates_time :time_end, presence: true, :on_or_after => :time_begin
  validates :location, presence: true
  validates :description, length: { maximum: 500 }  
  
  def expire?
    dt_end = DateTime.new(date_end.year, date_end.month, date_end.day, time_end.hour, time_end.min, time_end.sec)
    return dt_end < Time.now
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_parents
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:new, :create, :edit, :update, :destroy]
  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
    3.times { @event.pictures.build }
    @event.build_group
    @event.build_ticket
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.society_id = params[:society_id]
    respond_to do |format|
      if @event.save   
        format.html { redirect_to [@event.society, @event] }
        format.json { render action: 'show', status: :created, location: [@event.society, @event] }
      else
        3.times { @event.pictures.build }
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to [@event.society, @event] }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to [@society,:events] }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])      
    end
    
    def set_parents
      @society = Society.find(params[:society_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :type, :date_begin, :time_begin, :date_end, :time_end, 
      :location, :website, :description, group_attributes: [:id,:name,:societylist], 
      pictures_attributes: [:id, :picture], ticket_attributes: [:id, :total, :price])
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for [@society, @event] do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div> 
  <% end %>
  
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"text_field"%>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.select :type, options_for_select([["Expo"], ["Conferences"], ["Seminars"], ["Meeting"], ["Trade Show"], ["Business Dinners"], ["Networking"], ["Ceremony"], ["Theme Party"], ["Trade Fairs"]]), class:"text_field" %>
  </div>
  <div id="time_duration">
	    <%= f.label :time_duration %><br>
	    <input type="date" id="event_date_begin" name="event[date_begin]" class="date">
	    <input type="text" id="event_time_begin" name="event[time_begin]" class="time"> to 
	    <input type="date" id="event_date_end" name="event[date_end]" class="date">
	    <input type="text" id="event_time_end" name="event[time_end]" class="time">
  </div>
  
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location, class:"text_field"%>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website, class:"text_field"%>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class:"description_field"%>
  </div>
  
  <div class="group">
  	  <h3>Share Event With Group:</h3>
	  <%= f.fields_for :group do |g| %>  
	  	<div class="field">
			<%= g.label :name, "Group name"%><br>
			<%= g.text_field :name, class:"text_field"%>
		 </div>
		 <div class="field">
		  	<%= g.label :societylist, "Add societies"%><br>
			<%= g.text_field :societylist, class:"society_auto_complete text_field"%>
		</div>
	  <% end -%> 
  </div><br>
  
  <div class="picture">
	  <h3>Upload Pictures:</h3>
	  <%= f.fields_for :pictures do |p| %>  	
	  	<%= p.file_field :picture %> 
	  <% end -%>
  </div><br>
  
  <div class="ticket">
  	  <h3>Ticket Details:</h3>
	  <%= f.fields_for :ticket do |t| %>  
	  	<div class="field">
			<%= t.label :total, "Quantity"%><br>
			<%= t.number_field :total, class:"text_field"%>
		 </div>
		 <div class="field">
		  	<%= t.label :price, "Price"%><br>
			<%= t.number_field :price, step: "any", class:"text_field"%>
		</div>
	  <% end -%> 
  </div><br><br> 
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<h1>
  <%= @event.name %>
</h1>
<% if admin?(@society) %>
	<%= link_to 'Edit', [:edit, @society, @event], id: "button" %>
<% end %>
<%= link_to 'Reserve', new_society_event_reservation_path(@society, @event), id: "button" %>

<% if @event.pictures.count > 0 %>
	<ul class="bxslider">
	  <li><%= image_tag @event.pictures.first.try(:picture).try(:url, :large), class: "event_pictures" %></li>	
	  <li><%= image_tag @event.pictures.second.try(:picture).try(:url, :large), class: "event_pictures" %></li>	
	  <li><%= image_tag @event.pictures.third.try(:picture).try(:url, :large), class: "event_pictures" %></li>
	</ul>
<% end %>

<p>
  <strong>Type:</strong>
  <%= @event.type %>
</p>

<p>
  <strong>Begin time:</strong>
  <%= @event.date_begin.strftime("%m/%d/%Y") %>
  <%= @event.time_begin.strftime("%I:%M%p") %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.date_end.strftime("%m/%d/%Y") %>
  <%= @event.time_end.strftime("%I:%M%p") %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Website:</strong>
  <%= link_to @event.website, @event.website %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Remaining Tickets:</strong>
  <%= remain_ticket(@event) %>
</p>

<p>
  <strong>Tickets Price:</strong>
  <%= @event.ticket.try(:price) %>
</p>

<%= link_to 'New Comment', new_society_event_comment_path(@society, @event), id: "button" %>
<table>
  <thead>
    <tr>
    	<th>Poster</th>
      <th>Comments</th>
    </tr>
  </thead>
  <tbody>
    <% @event.comments.each do |comment| %>
      <tr>
      	<td><%= comment.member.name %></td>
        <td><%= comment.content %></td>
      </tr>
    <% end %>
  </tbody>
</table>