config/routes.rb
SMDProject::Application.routes.draw do

  root "pages#index"
  
  resources :sessions, only: [:new, :create, :destroy]  

  resources :members, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :messages, only: [:index, :new, :create, :show, :destroy]
    member do      
      get 'change_password'
      patch 'update_password'
    end
  end

  resources :societies do
    resources :events, only: [:new, :create, :show, :edit, :update, :destroy] do
      resources :reservations, only: [:new, :create, :show, :edit, :update, :destroy]
      resources :comments, only: [:new, :create]
    end
    get 'join', on: :member
    get 'autocomplete', on: :collection
  end
  
 
  match "/search", to: "pages#search", via: [:get, :post], as: :search  
  match "/events", to: "pages#event", via: [:get, :post], as: :eventslist
  match "/registration", to: "members#new", via: [:get, :post]
  match "/login", to: "sessions#new", via: [:get, :post]
  match "/logout", to: "sessions#destroy", via: [:get, :post]
  match "/pages/search_autocomplete", to: "pages#search_autocomplete", via: [:get, :post]

end

app/models/society.rb
class Society < ActiveRecord::Base
  has_many :joins
  has_many :events
  has_many :bearers
  has_many :members, through: :joins
  has_and_belongs_to_many :groups
  
  accepts_nested_attributes_for :joins, allow_destroy: true,
                      reject_if: proc { |attributes| attributes['role'].blank? }
  
  has_attached_file :logo, styles: { medium: "200x200>", small: "150x150>" }, 
                  default_url: "/images/missing_:style.png", 
                  preserve_files: true
  
  validates_attachment_content_type :logo, content_type: ['image/jpeg', 'image/jpg', 'image/png']
  validates_attachment_size :logo, :less_than => 4.megabytes
  
  validates :name, length: { maximum: 30 }, presence: true, uniqueness: { case_sensitive: false }
  validates :register_num, length: { is: 8 }, numericality: { only_integer: true }
  validates :description, length: { maximum: 500 }
end

app/controllers/societies_controller.rb
class SocietiesController < ApplicationController
  before_action :set_society, only: [:join, :show, :edit, :update, :destroy]
  before_action :require_login, only: [:new, :create, :join, :edit, :update, :destroy]
  
  # GET /societies/1/join
  def join 
    Join.create(member_id: current_member.id, 
        society_id: @society.id, role: "Member", admin: false)
    gflash :now, success: 'You joined this society successfully.'
    render "show"
  end  
    
  def autocomplete
    terms = params[:term].split(", ")
    term = terms.pop
    societies = Society.all.order(:name).where("name LIKE ?", "#{term}%")
    respond_to do |format|
      format.html
      format.json { render json: societies.map(&:name) - terms }
    end
  end  
  
  # GET /societies
  # GET /societies.json
  def index
    @societies = Society.all
  end

  # GET /societies/1
  # GET /societies/1.json
  def show
  end

  # GET /societies/new
  def new
      @society = Society.new
      representative = @society.joins.build
      representative.role = "Representative"
      representative.member = current_member
      representative.admin = true
      president = @society.joins.build
      president.role = "President"
      president.admin = true
      president.build_member unless president.member
      treasurer = @society.joins.build
      treasurer.role = "Treasurer"
      treasurer.build_member unless treasurer.member
  end

  # GET /societies/1/edit
  def edit
    join = Join.find_by_member_id_and_society_id(current_member.id, @society.id)
    if join.nil? || !join.admin
      flash :now, :error => "Only admin of society can edit details about society."
      render "show"
    end
  end

  # POST /societies
  # POST /societies.json
  def create
    @society = Society.new(society_params)
    respond_to do |format|
      if @society.save
        session[:society_id] = @society.id
        format.html { redirect_to @society }
        format.json { render action: 'show', status: :created, location: @society }
      else
        format.html { render action: 'new' }
        format.json { render json: @society.errors, status: :unprocessable_entity }
      end
    end    
  end

  # PATCH/PUT /societies/1
  # PATCH/PUT /societies/1.json
  def update
    respond_to do |format|
      if @society.update(society_params)
        format.html { redirect_to @society }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @society.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /societies/1
  # DELETE /societies/1.json
  def destroy
    @society.destroy
    respond_to do |format|
      format.html { redirect_to societies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_society
      @society = Society.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def society_params
      params.require(:society).permit(:name, :register_num, :website, :description, :logo, 
      joins_attributes: [:id, :role, :admin, :_destroy, member_attributes: [:id, :name, :email, :phone, :auto_generate]])
    end
end

app/helpers/societies_helper.rb
module SocietiesHelper
  
  def locked?(f)
    ["President","Treasurer","Representative"].include?(f.object.role)
  end
  
  def member_of?(society)
    current_member.nil? || !current_member.societies.include?(society)
  end
  
  def admin?(society)
    unless current_member.nil? || Join.find_by_member_id_and_society_id(current_member.id, society.id).nil?
      Join.find_by_member_id_and_society_id(current_member.id, society.id).admin
    end
  end
      
  def link_to_remove_member(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end
  
  def link_to_add_member(name, f)
    @join = f.object.joins.new    
    @join.build_member unless @join.member
    fields = f.fields_for("joins", @join, :child_index => "new_join") do |builder|
      render("join_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"join\", \"#{escape_javascript(fields)}\")")
  end
  
  def all_events(society)
    eventlist = Array.new
    society.events.each do |event|
      if !event.expire?
        eventlist << event
      end
    end
    society.groups.each do |group|
      if !group.event.expire?
        eventlist << group.event
      end
    end
    return eventlist.uniq
  end
end

app/views/societies/_form.html.erb
<%= form_for(@society) do |f| %>
  <% if @society.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@society.errors.count, "error") %> prohibited this society from being saved:</h2>

      <ul>
      <% @society.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
  	<%= f.label :logo %><br>
  	<%= f.file_field :logo %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"text_field"%>
  </div>
  <div class="field">
    <%= f.label :register_num %><br>
    <%= f.text_field :register_num, class:"text_field"%>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.url_field :website, class:"text_field"%>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class:"description_field"%>
  </div>
  
  <h3>Office Bearers</h3>  
  <table border="1">
	  <thead>
	    <tr>	      
	      <th>Name</th>
	      <th>Email</th>
	      <th>Phone</th>
	      <th>Role</th>
	      <th>Admin</th>
	      <th></th>
	    </tr>
	  </thead>
	  <tbody>
	  	<%= f.fields_for :joins do |builder| %>
			<%= render 'join_fields', :f => builder %>
  		<% end %>	
	  </tbody>	 
	  <tfoot>  		
	  	<tr>
  			<td><%= link_to_add_member "Add Bearer", f %></td>
  		</tr>  	
  	  </tfoot> 
  </table><br>
  <div class="actions">
    <%= f.submit %>
  </div>  
<% end %>

app/views/societies/_join_fields.html.erb
<tr>
	<%= f.fields_for :member do |g| %>
		 <td><%= g.text_field :name %></td>
		 <td><%= g.email_field :email %></td>
		 <td><%= g.text_field :phone %>
		 <%= g.hidden_field :auto_generate, value: "1" %></td> 
	<% end %>   
	<% if locked?(f) %>
		<td><%= f.text_field :role, readonly: true %></td>
		<td><%= f.check_box :admin %></td>
	<% else %>
		<td><%= f.text_field :role %></td>
		<td><%= f.check_box :admin %></td>
		<td><%= link_to_remove_member "Remove", f %></td>
	<% end %>
</tr>

app/views/societies/edit.html.erb
<h1>Editing society</h1>

<%= render 'form' %>

app/views/societies/index.html.erb
<h1>All Societies</h1>

<table border="1">
  <thead>
    <tr>
      <th>Society Name</th>
      <th>President</th>
      <th>No. of Members</th>
      <th>Website</th>
    </tr>
  </thead>
  <tbody>
    <% @societies.each do |society| %>
      <tr>
        <td><%= link_to society.name, society %></td>
        <td><%= Join.find_by_society_id_and_role(society.id,"President").member.name %></td>
        <td><%= society.joins.count %></td>
        <td><%= link_to society.website, society.website %></td>        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Society', new_society_path, id: "button" %>

app/views/societies/new.html.erb
<h1>New society</h1>

  <%= render 'form' %>

app/views/societies/show.html.erb
<div class="society_info">
	<%= image_tag @society.logo.url(:medium), class: "society_logo" %>	
	<div class="society_details">
		<h1>
		  <%= @society.name %>
		</h1>	
		<h5>
		  Number of Members: 
		  <%= @society.joins.count %>
		</h5>	
		<h5>
		  Website: 
		  <%= link_to @society.website, @society.website %>
		</h5>	
		<h5>
		  Description: 
		  <%= @society.description %>
		</h5>
		<% if member_of?(@society) %>
			<%= link_to "Join Society",join_society_path(@society), id: "button" %>
		<% end %>
		<% if admin?(@society) %>
			<%= link_to "Edit Society Details", edit_society_path(@society), id: "button" %>
		<% end %>
	</div>
</div>

<div class="bearer">
	<h2>Office Bearer</h2>
	<table>
		<thead>
		    <tr>	  
		      <th>Role</th>	    
		      <th>Name</th>
		      <th>Email</th>
		      <th>Phone</th>	      
		    </tr>
		</thead>
		<tbody>
			<% @society.members.each do |member| %>
			<tr>
				<td><%= Join.find_by_member_id_and_society_id(member.id,@society.id).role %></td>
				<td><%= member.name %></td>
				<td><%= member.email %></td>
				<td><%= member.phone %></td>
			</tr>		
			<% end %>
		</tbody>
	</table>
</div>
<div class="event">	
	<%if admin?(@society)%>
		<%= link_to "Create Event", new_society_event_path(@society), id: "button" %>
    <% end %>
	<table>
		<thead>
		    <tr>	  
		      <th>Name</th>	    
		      <th>Type</th>
		      <th>Host</th>
		      <th>Location</th>
		      <th>Status</th>
		    </tr>
		</thead>
		<tbody>
			<% @society.events.each do |event| %>
			<tr>
				<td><%= link_to event.name, [@society, event] %></td>
				<td><%= event.type %></td>
				<td><%= event.society.name %></td>
				<td><%= event.location %></td>
				<td>
					<% if event.expire? %>
					Expired
					<% else %>
					Open
					<% end %>
				</td>
			</tr>		
			<% end %>
		</tbody>
	</table>
</div>