config/routes.rb
SMDProject::Application.routes.draw do

  root "pages#index"
  
  resources :sessions, only: [:new, :create, :destroy]  

  resources :members, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :messages, only: [:index, :new, :create, :show, :destroy]
    member do      
      get 'change_password'
      patch 'update_password'
    end
  end

  resources :societies do
    resources :events, only: [:new, :create, :show, :edit, :update, :destroy] do
      resources :reservations, only: [:new, :create, :show, :edit, :update, :destroy]
      resources :comments, only: [:new, :create]
    end
    get 'join', on: :member
    get 'autocomplete', on: :collection
  end
  
 
  match "/search", to: "pages#search", via: [:get, :post], as: :search  
  match "/events", to: "pages#event", via: [:get, :post], as: :eventslist
  match "/registration", to: "members#new", via: [:get, :post]
  match "/login", to: "sessions#new", via: [:get, :post]
  match "/logout", to: "sessions#destroy", via: [:get, :post]
  match "/pages/search_autocomplete", to: "pages#search_autocomplete", via: [:get, :post]

end

app/views/layouts/_footer.html.erb
<footer>
	<div class="footer_info">
		<p>Designed by: Fei Tang, Kimple Ke, Perry Yu</p>
		<p>University of Melbourne</p>
		<p>SWEN30006 Software Modeling and Design</p>
		<p>Copyright &copy; 2014</p>	
	</div>
</footer>

app/views/layouts/_header.html.erb
<header>
	<div class="banner_top row">
		<div class="col-md-8">
			<div class="logo">
				<%= image_tag("logo.png",alt: "Club-biz logo", class: "round") %>
			</div>			
		</div>
		<%= render 'layouts/login' %>
	</div>
	<div class="banner_second row">
		<%= render 'layouts/menu' %>
		<%= render 'layouts/search' %>
	</div>
</header>

app/views/layouts/_login.html.erb
<div class="login col-md-4">
	<% if logged_in? %>
		<p><%= link_to "Profile", current_member %> 
		<%if unread_message_count > 0 %>
			<strong><%= link_to "Messages(#{unread_message_count})", [current_member, :messages], class: "pulsate message" %></strong>
		<% else %>
			<%= link_to "Messages(#{unread_message_count})", [current_member, :messages], class: "message" %>
		<% end %>
		<%= link_to "Logout", logout_path %>
		<span class="glyphicon glyphicon-user"></span> </p>
	<% else %>
		<p><%= link_to "Login", login_path %>
			<span class="glyphicon glyphicon-user"></span> </p>
	<% end %>
</div>

app/views/layouts/_menu.html.erb
<div class="menu col-md-6">
	<%= render_navigation expand_all: true do |primary| %>
		<% primary.item :home, 'Home', root_path do |sec| %>
			<%if logged_in? %>
				<% sec.item :profile, 'Profile', url_for(current_member) %>
				<% sec.item :profile, 'Message', [current_member, :messages] %>	
				<% sec.item :profile, 'Log Out', logout_path %>
			<% else %>
				<% sec.item :profile, 'Login', login_path %>
				<% sec.item :profile, 'Sign Up', registration_path %>
			<% end %>
		<% end %>		
		<% primary.item :societies, 'Societies', societies_path do |sec| %>
			<% sec.item :my_societies, 'My Societies',if: proc {logged_in?} do |s| %>
				<% current_member.societies.uniq.take(10).each do |society| %>
					<% s.item :society, society.name, url_for(society) %>
				<% end %>
			<% end %>
			<% sec.item :hot_societies, 'Popular Societies' do |s| %>
				<% Society.all.sort_by{|society| society.joins.count}.take(10).each do |society| %>
					<% s.item :society, society.name, url_for(society) %>
				<% end %>
			<% end %>
			<% sec.item :new_society, 'Create Society', new_society_path, if: proc {logged_in?} %>
		<% end %>
		<% primary.item :events, 'Events', eventslist_path do |sec| %>
			<% sec.item :reserved_events, 'Rerserved Events',if: proc {logged_in?} do |e| %>
				<% current_member.reservations.collect{|res| res.event}.uniq.take(10).each do |event| %>
					<% e.item :event, event.name, [event.society, event] %>
				<% end %>				
			<% end %>
			<% sec.item :hot_events, 'Hot Events' do |e| %>
				<% Event.all.sort_by{|event| event.reservations.count}.take(10).each do |event| %>
					<% e.item :event, event.name, [event.society, event] %>
				<% end %>
			<% end %>
		<% end %>
	<% end %>
</div>		

app/views/layouts/_search.html.erb
<div class= "search">
	<%= form_tag("/search", method: "get") do %>
	  <%= label_tag(:search, "Search for:") %>
	  <%= select_tag(:search_method, options_for_select([["Event"], ["Society"], ["Event by society"], ["Event by type"]]), class:"select_box")%>
	  <%= search_field_tag (:search_input) %>
	  <%= submit_tag("Search") %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SMDProject</title>  
  <%= stylesheet_link_tag "blueprint/print",media: "print" %>
  <%= stylesheet_link_tag "blueprint/screen",media: "screen" %>   
  <%= stylesheet_link_tag "bootstrap",media: "all" %>  
  <%= stylesheet_link_tag "bootstrap.min",media: "all" %> 
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>    
  <%= javascript_include_tag "superfish" %>
  <%= javascript_include_tag "hoverIntent" %>
  <%= javascript_include_tag "bootstrap" %>
  <%= javascript_include_tag "bootstrap.min" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>	
	<div class="page">
		<%= gflash %>
		<%= render 'layouts/header' %>	
		<div class="container">	
			<div class="row">				
				<div class="content offset4 span4">
					<%= yield %>
				</div>		
			</div>
		</div>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>