config/routes.rb
SMDProject::Application.routes.draw do

  root "pages#index"
  
  resources :sessions, only: [:new, :create, :destroy]  

  resources :members, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :messages, only: [:index, :new, :create, :show, :destroy]
    member do      
      get 'change_password'
      patch 'update_password'
    end
  end

  resources :societies do
    resources :events, only: [:new, :create, :show, :edit, :update, :destroy] do
      resources :reservations, only: [:new, :create, :show, :edit, :update, :destroy]
      resources :comments, only: [:new, :create]
    end
    get 'join', on: :member
    get 'autocomplete', on: :collection
  end
  
 
  match "/search", to: "pages#search", via: [:get, :post], as: :search  
  match "/events", to: "pages#event", via: [:get, :post], as: :eventslist
  match "/registration", to: "members#new", via: [:get, :post]
  match "/login", to: "sessions#new", via: [:get, :post]
  match "/logout", to: "sessions#destroy", via: [:get, :post]
  match "/pages/search_autocomplete", to: "pages#search_autocomplete", via: [:get, :post]

end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :joins
  has_many :societies, through: :joins
  has_many :events, through: :societies
  has_many :reservations
  has_many :comments 
  has_many :sended_message, :class_name => "Message", :foreign_key => "sender_id"
  has_many :received_message, :class_name => "Message", :foreign_key => "receiver_id"
  has_secure_password
  
  attr_accessor :old_password, :auto_generate
   
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :email, presence: true,
                    format: { with: email_regex },
                    uniqueness: { case_sensitive: false },
                    on: :create
  
  validates :password, length: { minimum: 6 }, 
                       allow_nil: true,
                       on: :create
                       
  validates :name, presence: true,
                   length: { maximum: 30 }
  
  validates :student_id, length: { maximum: 6 }
  
  validates :phone, length: { maximum: 13 } 
  
  before_validation :generate_password
    
  def generate_password
    if self.new_record? && self.auto_generate == "1"
      self.password = (0...8).map { (65 + rand(26)).chr }.join
      self.password_confirmation = self.password      
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy, :change_password, :update_password]
  before_action :require_login, only: [:show, :edit, :update, :destroy, :change_password, :update_password]
  before_action :require_self, only: [:edit, :update, :destroy, :change_password, :update_password]
  
  def require_self
    if current_member != @member
      redirect_to @member
    end
  end
  
  # GET /members/1/change_password
  def change_password
    
  end
  
  # Post /members/1/update_password
  def update_password
    if @member.authenticate(params[:member][:old_password])
      if (params[:member][:password] == params[:member][:password_confirmation])
          @member.password_digest = BCrypt::Password.create(params[:member][:password])
          if @member.save
            redirect_to @member
          else
            gflash :now, error: "Password update failed."
            render 'change_password'
          end
      else
            gflash :now, error: "New password and password confirmation mismatch."
            render 'change_password'
      end
    else
        gflash :now, error: "Invalid old password."
        render 'change_password'
    end
  end
  
  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
    
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(create_params)
    respond_to do |format|
      if @member.save
        session[:member_id] = @member.id
        format.html { redirect_to @member }
        format.json { render action: 'show', status: :created, location: @member }
      else
        format.html { render action: 'new' }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(update_params)
        format.html { redirect_to @member }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    session[:member_id] = nil
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end
    
    def create_params
      params.require(:member).permit(:email, :password, :password_confirmation, :name, :student_id, :phone)
    end
    
    def update_params
      params.require(:member).permit(:name, :student_id, :phone)
    end
      
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/change_password.html.erb
<h1>Change Password</h1>

<%= form_for @member, :url => update_password_member_path(@member) do |f| %>
	<div class="field">
		<%= f.label :old_password %><br />
		<%= f.password_field :old_password, class:"text_field"%>
	</div>
	<div class="field">
		<%= f.label :password, "New password" %><br />
		<%= f.password_field :password, class:"text_field"%>
	</div>
	<div class="field">
		<%= f.label :password_confirmation %><br />
		<%= f.password_field :password_confirmation, class:"text_field"%>
	</div><br>
	<div class="actions"> 
    	<%= f.submit "Change Password" %>
  	</div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"text_field"%>
  </div>
  <div class="field">
    <%= f.label :student_id, "Student ID" %><br>
    <%= f.text_field :student_id, class:"text_field"%>
  </div>
  <div class="field">
    <%= f.label :phone, "Phone Number" %><br>
    <%= f.text_field :phone, class:"text_field"%>
  </div><br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/new.html.erb
<h1>Registration</h1>

<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email, class:"text_field"%>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password, class:"text_field"%>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation, class:"text_field"%>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"text_field"%>
  </div>
  <div class="field">
    <%= f.label :student_id, "Student ID" %><br>
    <%= f.text_field :student_id, class:"text_field"%>
  </div>
  <div class="field">
    <%= f.label :phone, "Phone Number" %><br>
    <%= f.telephone_field :phone, class:"text_field"%>
  </div><br>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/members/show.html.erb
<h1>Welcome to Club-biz!</h1>
<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Student ID:</strong>
  <%= @member.student_id %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @member.phone %>
</p>
<% if @member == current_member%>
	<p>You Have <strong><%= unread_message_count %></strong> Unread Messages.</p>
	<%= link_to 'View Messages', [current_member, :messages], id: "button" %>
	<%= link_to 'Edit Details', edit_member_path(@member), id: "button" %>
	<%= link_to 'Change Password', change_password_member_path(@member), id: "button" %>	
<% end %>

<h3>Societies</h3>
<table>
	<thead>
	    <tr>	  	      	    
	      <th>Soicety Name</th>
	      <th>Role</th>
	      <th>Website</th>	
	      <th></th>      
	    </tr>
	</thead>
	<tbody>
		<% current_member.joins.each do |join| %>
		<tr>
			<td><%= link_to join.society.name, join.society %></td>
			<td><%= join.role %></td>
			<td><%= link_to join.society.website, join.society.website %></td>
			<td></td>
		</tr>		
		<% end %>
	</tbody>
</table>

<h3>Reservations</h3>
<table>
	<thead>
	    <tr>	  	      	    
	      <th>Event Name</th>
	      <th>Host by</th>
	      <th>Quantity</th>	
	      <th></th>      
	    </tr>
	</thead>
	<tbody>
		<% current_member.reservations.each do |res| %>
		<tr>
			<td><%= link_to res.event.name, [res.event.society, res.event] %></td>
			<td><%= link_to res.event.society.name, res.event.society %></td>
			<td><%= res.quantity %></td>
			<td><%= link_to 'Delete', [res.event.society, res.event, res], method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>		
		<% end %>
	</tbody>
</table>